### ISSUE TITLE
YARA accepts duplicate string identifiers

### ISSUE THREAD

**Issue by aschuster99** [plusvic/yara#369] opened 2015-11-12 13:46 UTC
To my surprise, YARA 3.4.0 does not complain about duplicate string identifiers. Is this behavior intended?

$ cat test.yar
rule test
{
    strings:
        $match = "foo"
        $match = "bar"
        $match = "baz"
    condition:
        any of them
}

$ yara -s test.yar test.yar
test test.yar
0x22:$match: foo
0x33:$match: bar
0x44:$match: baz

I expected this code to trigger a duplicate string identifier error.

Thanks!
Andreas

**Comment by plusvic** [comment] 2016-01-22 20:42
Fixed in f867aee70cf52e1ea70ee7b4c2deee09a6cb10b8

**Closed by plusvic** 2016-01-22 20:42 UTC

**Comment by 2xyo** [comment] 2016-01-31 16:04
@plusvic:  does this fix should also complains with [anonymous strings](https://yara.readthedocs.org/en/latest/writingrules.html#using-anonymous-strings-with-of-and-for-of)?

Because there is maybe a regression according to nbs-system/php-malware-finder#14.

**Comment by plusvic** [comment] 2016-01-31 21:52
You're right. I solved this regression in commit 52dd72e05afe4a878f8bd5000e122247058fc751
